// Generated by gencpp from file jrc_srvs/call_grasp.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_CALL_GRASP_H
#define JRC_SRVS_MESSAGE_CALL_GRASP_H

#include <ros/service_traits.h>


#include <jrc_srvs/call_graspRequest.h>
#include <jrc_srvs/call_graspResponse.h>


namespace jrc_srvs
{

struct call_grasp
{

typedef call_graspRequest Request;
typedef call_graspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct call_grasp
} // namespace jrc_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jrc_srvs::call_grasp > {
  static const char* value()
  {
    return "f6453fb762d13fe85f432f25bd98a414";
  }

  static const char* value(const ::jrc_srvs::call_grasp&) { return value(); }
};

template<>
struct DataType< ::jrc_srvs::call_grasp > {
  static const char* value()
  {
    return "jrc_srvs/call_grasp";
  }

  static const char* value(const ::jrc_srvs::call_grasp&) { return value(); }
};


// service_traits::MD5Sum< ::jrc_srvs::call_graspRequest> should match 
// service_traits::MD5Sum< ::jrc_srvs::call_grasp > 
template<>
struct MD5Sum< ::jrc_srvs::call_graspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::call_grasp >::value();
  }
  static const char* value(const ::jrc_srvs::call_graspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::call_graspRequest> should match 
// service_traits::DataType< ::jrc_srvs::call_grasp > 
template<>
struct DataType< ::jrc_srvs::call_graspRequest>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::call_grasp >::value();
  }
  static const char* value(const ::jrc_srvs::call_graspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jrc_srvs::call_graspResponse> should match 
// service_traits::MD5Sum< ::jrc_srvs::call_grasp > 
template<>
struct MD5Sum< ::jrc_srvs::call_graspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::call_grasp >::value();
  }
  static const char* value(const ::jrc_srvs::call_graspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::call_graspResponse> should match 
// service_traits::DataType< ::jrc_srvs::call_grasp > 
template<>
struct DataType< ::jrc_srvs::call_graspResponse>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::call_grasp >::value();
  }
  static const char* value(const ::jrc_srvs::call_graspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JRC_SRVS_MESSAGE_CALL_GRASP_H
