// Generated by gencpp from file jrc_srvs/call_twist.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_CALL_TWIST_H
#define JRC_SRVS_MESSAGE_CALL_TWIST_H

#include <ros/service_traits.h>


#include <jrc_srvs/call_twistRequest.h>
#include <jrc_srvs/call_twistResponse.h>


namespace jrc_srvs
{

struct call_twist
{

typedef call_twistRequest Request;
typedef call_twistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct call_twist
} // namespace jrc_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jrc_srvs::call_twist > {
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::jrc_srvs::call_twist&) { return value(); }
};

template<>
struct DataType< ::jrc_srvs::call_twist > {
  static const char* value()
  {
    return "jrc_srvs/call_twist";
  }

  static const char* value(const ::jrc_srvs::call_twist&) { return value(); }
};


// service_traits::MD5Sum< ::jrc_srvs::call_twistRequest> should match 
// service_traits::MD5Sum< ::jrc_srvs::call_twist > 
template<>
struct MD5Sum< ::jrc_srvs::call_twistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::call_twist >::value();
  }
  static const char* value(const ::jrc_srvs::call_twistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::call_twistRequest> should match 
// service_traits::DataType< ::jrc_srvs::call_twist > 
template<>
struct DataType< ::jrc_srvs::call_twistRequest>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::call_twist >::value();
  }
  static const char* value(const ::jrc_srvs::call_twistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jrc_srvs::call_twistResponse> should match 
// service_traits::MD5Sum< ::jrc_srvs::call_twist > 
template<>
struct MD5Sum< ::jrc_srvs::call_twistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::call_twist >::value();
  }
  static const char* value(const ::jrc_srvs::call_twistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::call_twistResponse> should match 
// service_traits::DataType< ::jrc_srvs::call_twist > 
template<>
struct DataType< ::jrc_srvs::call_twistResponse>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::call_twist >::value();
  }
  static const char* value(const ::jrc_srvs::call_twistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JRC_SRVS_MESSAGE_CALL_TWIST_H
