// Generated by gencpp from file jrc_srvs/call_graspRequest.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_CALL_GRASPREQUEST_H
#define JRC_SRVS_MESSAGE_CALL_GRASPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jrc_srvs
{
template <class ContainerAllocator>
struct call_graspRequest_
{
  typedef call_graspRequest_<ContainerAllocator> Type;

  call_graspRequest_()
    : grasp(false)  {
    }
  call_graspRequest_(const ContainerAllocator& _alloc)
    : grasp(false)  {
  (void)_alloc;
    }



   typedef uint8_t _grasp_type;
  _grasp_type grasp;





  typedef boost::shared_ptr< ::jrc_srvs::call_graspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::call_graspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct call_graspRequest_

typedef ::jrc_srvs::call_graspRequest_<std::allocator<void> > call_graspRequest;

typedef boost::shared_ptr< ::jrc_srvs::call_graspRequest > call_graspRequestPtr;
typedef boost::shared_ptr< ::jrc_srvs::call_graspRequest const> call_graspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::call_graspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::call_graspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::call_graspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::call_graspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb3ac9f2d2f64667074ec82e617b09f2";
  }

  static const char* value(const ::jrc_srvs::call_graspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb3ac9f2d2f64667ULL;
  static const uint64_t static_value2 = 0x074ec82e617b09f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/call_graspRequest";
  }

  static const char* value(const ::jrc_srvs::call_graspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool grasp\n\
";
  }

  static const char* value(const ::jrc_srvs::call_graspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct call_graspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::call_graspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::call_graspRequest_<ContainerAllocator>& v)
  {
    s << indent << "grasp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_CALL_GRASPREQUEST_H
