// Generated by gencpp from file jrc_srvs/call_graspResponse.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_CALL_GRASPRESPONSE_H
#define JRC_SRVS_MESSAGE_CALL_GRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jrc_srvs
{
template <class ContainerAllocator>
struct call_graspResponse_
{
  typedef call_graspResponse_<ContainerAllocator> Type;

  call_graspResponse_()
    : acted(false)  {
    }
  call_graspResponse_(const ContainerAllocator& _alloc)
    : acted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _acted_type;
  _acted_type acted;





  typedef boost::shared_ptr< ::jrc_srvs::call_graspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::call_graspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct call_graspResponse_

typedef ::jrc_srvs::call_graspResponse_<std::allocator<void> > call_graspResponse;

typedef boost::shared_ptr< ::jrc_srvs::call_graspResponse > call_graspResponsePtr;
typedef boost::shared_ptr< ::jrc_srvs::call_graspResponse const> call_graspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::call_graspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::call_graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::call_graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::call_graspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9cffd1eb0784577656f95ec0b26770";
  }

  static const char* value(const ::jrc_srvs::call_graspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9cffd1eb078457ULL;
  static const uint64_t static_value2 = 0x7656f95ec0b26770ULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/call_graspResponse";
  }

  static const char* value(const ::jrc_srvs::call_graspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool acted\n\
\n\
";
  }

  static const char* value(const ::jrc_srvs::call_graspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct call_graspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::call_graspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::call_graspResponse_<ContainerAllocator>& v)
  {
    s << indent << "acted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_CALL_GRASPRESPONSE_H
