// Generated by gencpp from file jrc_srvs/graspResponse.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_GRASPRESPONSE_H
#define JRC_SRVS_MESSAGE_GRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace jrc_srvs
{
template <class ContainerAllocator>
struct graspResponse_
{
  typedef graspResponse_<ContainerAllocator> Type;

  graspResponse_()
    : result()  {
    }
  graspResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::jrc_srvs::graspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::graspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct graspResponse_

typedef ::jrc_srvs::graspResponse_<std::allocator<void> > graspResponse;

typedef boost::shared_ptr< ::jrc_srvs::graspResponse > graspResponsePtr;
typedef boost::shared_ptr< ::jrc_srvs::graspResponse const> graspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::graspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::graspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::graspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::graspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2420602a83d8ccc0f3664e0daafab6c";
  }

  static const char* value(const ::jrc_srvs::graspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2420602a83d8cccULL;
  static const uint64_t static_value2 = 0x0f3664e0daafab6cULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/graspResponse";
  }

  static const char* value(const ::jrc_srvs::graspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool result\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::jrc_srvs::graspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::graspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::graspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::graspResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_GRASPRESPONSE_H
