// Generated by gencpp from file jrc_srvs/poseResponse.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_POSERESPONSE_H
#define JRC_SRVS_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jrc_srvs
{
template <class ContainerAllocator>
struct poseResponse_
{
  typedef poseResponse_<ContainerAllocator> Type;

  poseResponse_()
    : product(0)  {
    }
  poseResponse_(const ContainerAllocator& _alloc)
    : product(0)  {
  (void)_alloc;
    }



   typedef int64_t _product_type;
  _product_type product;





  typedef boost::shared_ptr< ::jrc_srvs::poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jrc_srvs::poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct poseResponse_

typedef ::jrc_srvs::poseResponse_<std::allocator<void> > poseResponse;

typedef boost::shared_ptr< ::jrc_srvs::poseResponse > poseResponsePtr;
typedef boost::shared_ptr< ::jrc_srvs::poseResponse const> poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jrc_srvs::poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jrc_srvs::poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jrc_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jrc_srvs::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jrc_srvs::poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jrc_srvs::poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jrc_srvs::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0999a385a89125a9804d02fa52c82670";
  }

  static const char* value(const ::jrc_srvs::poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0999a385a89125a9ULL;
  static const uint64_t static_value2 = 0x804d02fa52c82670ULL;
};

template<class ContainerAllocator>
struct DataType< ::jrc_srvs::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jrc_srvs/poseResponse";
  }

  static const char* value(const ::jrc_srvs::poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jrc_srvs::poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 product\n\
";
  }

  static const char* value(const ::jrc_srvs::poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jrc_srvs::poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.product);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jrc_srvs::poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jrc_srvs::poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "product: ";
    Printer<int64_t>::stream(s, indent + "  ", v.product);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JRC_SRVS_MESSAGE_POSERESPONSE_H
