// Generated by gencpp from file jrc_srvs/reco.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_RECO_H
#define JRC_SRVS_MESSAGE_RECO_H

#include <ros/service_traits.h>


#include <jrc_srvs/recoRequest.h>
#include <jrc_srvs/recoResponse.h>


namespace jrc_srvs
{

struct reco
{

typedef recoRequest Request;
typedef recoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reco
} // namespace jrc_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jrc_srvs::reco > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::jrc_srvs::reco&) { return value(); }
};

template<>
struct DataType< ::jrc_srvs::reco > {
  static const char* value()
  {
    return "jrc_srvs/reco";
  }

  static const char* value(const ::jrc_srvs::reco&) { return value(); }
};


// service_traits::MD5Sum< ::jrc_srvs::recoRequest> should match 
// service_traits::MD5Sum< ::jrc_srvs::reco > 
template<>
struct MD5Sum< ::jrc_srvs::recoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::reco >::value();
  }
  static const char* value(const ::jrc_srvs::recoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::recoRequest> should match 
// service_traits::DataType< ::jrc_srvs::reco > 
template<>
struct DataType< ::jrc_srvs::recoRequest>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::reco >::value();
  }
  static const char* value(const ::jrc_srvs::recoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jrc_srvs::recoResponse> should match 
// service_traits::MD5Sum< ::jrc_srvs::reco > 
template<>
struct MD5Sum< ::jrc_srvs::recoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::reco >::value();
  }
  static const char* value(const ::jrc_srvs::recoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::recoResponse> should match 
// service_traits::DataType< ::jrc_srvs::reco > 
template<>
struct DataType< ::jrc_srvs::recoResponse>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::reco >::value();
  }
  static const char* value(const ::jrc_srvs::recoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JRC_SRVS_MESSAGE_RECO_H
