// Generated by gencpp from file jrc_srvs/rgbd.msg
// DO NOT EDIT!


#ifndef JRC_SRVS_MESSAGE_RGBD_H
#define JRC_SRVS_MESSAGE_RGBD_H

#include <ros/service_traits.h>


#include <jrc_srvs/rgbdRequest.h>
#include <jrc_srvs/rgbdResponse.h>


namespace jrc_srvs
{

struct rgbd
{

typedef rgbdRequest Request;
typedef rgbdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rgbd
} // namespace jrc_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jrc_srvs::rgbd > {
  static const char* value()
  {
    return "4eef606dcba8e10e7c0e4a74324986c4";
  }

  static const char* value(const ::jrc_srvs::rgbd&) { return value(); }
};

template<>
struct DataType< ::jrc_srvs::rgbd > {
  static const char* value()
  {
    return "jrc_srvs/rgbd";
  }

  static const char* value(const ::jrc_srvs::rgbd&) { return value(); }
};


// service_traits::MD5Sum< ::jrc_srvs::rgbdRequest> should match 
// service_traits::MD5Sum< ::jrc_srvs::rgbd > 
template<>
struct MD5Sum< ::jrc_srvs::rgbdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::rgbd >::value();
  }
  static const char* value(const ::jrc_srvs::rgbdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::rgbdRequest> should match 
// service_traits::DataType< ::jrc_srvs::rgbd > 
template<>
struct DataType< ::jrc_srvs::rgbdRequest>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::rgbd >::value();
  }
  static const char* value(const ::jrc_srvs::rgbdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jrc_srvs::rgbdResponse> should match 
// service_traits::MD5Sum< ::jrc_srvs::rgbd > 
template<>
struct MD5Sum< ::jrc_srvs::rgbdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jrc_srvs::rgbd >::value();
  }
  static const char* value(const ::jrc_srvs::rgbdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jrc_srvs::rgbdResponse> should match 
// service_traits::DataType< ::jrc_srvs::rgbd > 
template<>
struct DataType< ::jrc_srvs::rgbdResponse>
{
  static const char* value()
  {
    return DataType< ::jrc_srvs::rgbd >::value();
  }
  static const char* value(const ::jrc_srvs::rgbdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JRC_SRVS_MESSAGE_RGBD_H
